[package]
name = "pong"
version = "0.1.0"
authors = ["Brock Szuszczewicz <brock@szu.email>"]
edition = "2021"
publish = false

[dependencies]
iced = "0.8.0"
iced_native = "0.9.1"
cosmic-time = { path = "../.."}
once_cell = "1.17"
rand = "0.8.5"
